site_name: Yvonne Tool & App Documentation Template
nav:
    - Home: index.md
    - Checklist REMOVE When Done: Template -Checklist - Creating Software Documentation.md
    - Getting Started: Template - Getting Started.md
    - How To: Template - How To.md
    - Reference Guide: Template - Reference Guide.md
    - Code Page: Template - Code Documentation.md
    - Source Code: https://github.com/YvonneBeirneFitzGerald/Tool-App-Documention-Templates
    - Style Guide: Template - Style Guide.md
    - About: Template - About The Creators.md
    - Feedback Page: Template - Feedback.md
    - Feedback: add https of google form link nothing needs to be added
theme: readthedocs
