site_name: Yvonne Tool & App Documentation Template
nav:
    - Home: index.md
    - Checklist REMOVE When Done: Template -Checklist - Creating Software Documentation.md
    - Getting Started: Template - Getting Started.md
    - How To: Template - How To.md
    - Reference Guide: Template - Reference Guide.md
    - FAQ: Template - FAQ.md
    - Code: Template - Code Main Page.md
    - Code Page: Template - Code Documentation.md
    - Source Code: https://github.com/YvonneBeirneFitzGerald/Tool-App-Documention-Templates
    - About: Template - About The Creators.md
    - Style Guide: Template - Style Guide.md
    - Feedback: Template - Feedback.md
    - Release Notes: Template - Release Notes.md
    - Keeping Up To Date: Template - Keeping Up To Date.md
theme:
    name: readthedocs
    prev_next_buttons_location: both

